// <auto-generated />
using System;
using CarRentalService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarRentalService.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CarRentalDbContext))]
    [Migration("20251201174314_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarRentalService.Infrastructure.Entities.ModelGenerationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("EngineVolume")
                        .HasColumnType("decimal(3,1)");

                    b.Property<decimal>("RentalPricePerHour")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Transmission")
                        .HasColumnType("integer");

                    b.Property<Guid>("VehicleModelId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleModelId", "Year")
                        .IsUnique();

                    b.ToTable("model_generations", (string)null);
                });

            modelBuilder.Entity("CarRentalService.Infrastructure.Entities.RentalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationHours")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RentStartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RenterId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RentStartTime");

                    b.HasIndex("RenterId");

                    b.HasIndex("VehicleId");

                    b.ToTable("rentals", (string)null);
                });

            modelBuilder.Entity("CarRentalService.Infrastructure.Entities.RenterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("LicenseNumber")
                        .IsUnique();

                    b.ToTable("renters", (string)null);
                });

            modelBuilder.Entity("CarRentalService.Infrastructure.Entities.VehicleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<Guid>("ModelGenerationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("ModelGenerationId");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("CarRentalService.Infrastructure.Entities.VehicleModelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BodyType")
                        .HasColumnType("integer");

                    b.Property<int>("DriveType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SeatCount")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleClass")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("vehicle_models", (string)null);
                });

            modelBuilder.Entity("CarRentalService.Infrastructure.Entities.ModelGenerationEntity", b =>
                {
                    b.HasOne("CarRentalService.Infrastructure.Entities.VehicleModelEntity", "VehicleModel")
                        .WithMany("ModelGenerations")
                        .HasForeignKey("VehicleModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("VehicleModel");
                });

            modelBuilder.Entity("CarRentalService.Infrastructure.Entities.RentalEntity", b =>
                {
                    b.HasOne("CarRentalService.Infrastructure.Entities.RenterEntity", "Renter")
                        .WithMany("Rentals")
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRentalService.Infrastructure.Entities.VehicleEntity", "Vehicle")
                        .WithMany("Rentals")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Renter");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarRentalService.Infrastructure.Entities.VehicleEntity", b =>
                {
                    b.HasOne("CarRentalService.Infrastructure.Entities.ModelGenerationEntity", "ModelGeneration")
                        .WithMany("Vehicles")
                        .HasForeignKey("ModelGenerationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ModelGeneration");
                });

            modelBuilder.Entity("CarRentalService.Infrastructure.Entities.ModelGenerationEntity", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarRentalService.Infrastructure.Entities.RenterEntity", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("CarRentalService.Infrastructure.Entities.VehicleEntity", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("CarRentalService.Infrastructure.Entities.VehicleModelEntity", b =>
                {
                    b.Navigation("ModelGenerations");
                });
#pragma warning restore 612, 618
        }
    }
}
