<Project Sdk="Microsoft.NET.Sdk.Worker">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="Properties\launchSettings.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Confluent.Kafka" Version="13.1.0" />
		<PackageReference Include="Bogus" Version="35.6.3" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CarRentalService.Application\CarRentalService.Application.csproj" />
		<ProjectReference Include="..\CarRentalService.ServiceDefaults\CarRentalService.ServiceDefaults.csproj" />
	</ItemGroup>

</Project>