<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.3.1" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="13.1.0" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.1.0" />
	  <PackageReference Include="Aspire.Hosting.Kafka" Version="13.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CarRentalService.Api.Host\CarRentalService.Api.Host.csproj" />
	  <ProjectReference Include="..\CarRentalService.Generator.Kafka\CarRentalService.Generator.Kafka.csproj" />
  </ItemGroup>

</Project>